# left is the alias name in excel file and in the application
# right is the real name in the Bladed project file

Wind_file: WINDF
Wind_direction_rad: WDIR
Inflow_angle_rad: FLINC
Vertical_shear: WSHEAR
